name: Generate Readme.md

on:
    pull_request:
    push:
        branches: [main]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: write

jobs:
    generate-readme:
        name: Generate README.md
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo with full history
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            # Setup Bun
            - name: Uses Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.23

            # Cache Bun dependencies
            - name: Cache Bun
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.bun
                      bun.lockb
                  key: bun-deps-${{ hashFiles('bun.lockb') }}
                  restore-keys: |
                      bun-deps-

            # Install dependencies
            - name: Install dependencies
              run: bun install

            # Configure Git
            - name: Configure Git for github-actions
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            # Run README generator and push changes
            - name: Run Readme script generator
              run: |
                  bun run ./scripts/generate-readme.ts
                  git add README.md
                  git diff --cached --quiet || git commit -m "(CI) README updated"
                  git push --force
