
name: Generate Readme.md

on: 
  pull_request:
  push:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: write

jobs:
  generate-readme:
    name: Generate README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: 'Uses Node'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Configure Git for github-actions"
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

      - name: Run Readme script generator
        run: |
          node ./scripts/generate-readme.js
          git add README.md
          git commit -m "(CI) README updated"
          git push